name: Update PY

on:
  schedule:
    - cron: '0 */8 * * *'  # 每8小时运行一次
      timezone: Asia/Shanghai
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install pyaes requests

    - name: Run update script
      run: python py.py

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "actions@github.com"
        git add nodes.txt update_history.md
        git commit -m "Auto update: $(date +'%Y-%m-%d %H:%M:%S')"
        git push

    - name: WeChat Work Notification
      env:
        WEBHOOK_URL: ${{ secrets.WECHAT_WEBHOOK }}
      run: |
        UPDATE_TIME=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')

        # 一次性读取所需信息
        read -r -d '' NEW_NODES TOTAL_NODES LATEST_NODES << EOF
        $(tail -n 4 update_history.md | grep -oP '新增节点数: \K\d+' | tail -1 || echo 0)
        $(wc -l < nodes.txt)
        $(tail -n 5 nodes.txt | sed 's/"/\\"/g')
        EOF

        # 构建消息内容 (根据新增节点数判断)
        if [ "$NEW_NODES" -gt 0 ]; then
            MESSAGE_CONTENT="**🔄 节点更新通知**\n
            > **更新时间**: \`${UPDATE_TIME}\`\n
            > **新增节点数**: \`${NEW_NODES}\`\n
            > **节点总数**: \`${TOTAL_NODES}\`\n\n
            **最新节点列表**:\n
            \`\`\`\n
            ${LATEST_NODES}
            \`\`\`\n
            [查看更新详情](https://github.com/${{ github.repository }}/commits/main)"
        else
          MESSAGE_CONTENT="**🔄 节点更新通知**\n
            > **更新时间**: \`${UPDATE_TIME}\`\n
            > 本次更新无新增节点。\n
            > **节点总数**: \`${TOTAL_NODES}\`\n
            [查看更新详情](https://github.com/${{ github.repository }}/commits/main)"
        fi

        MESSAGE_JSON=$(jq -n \
          --arg content "$MESSAGE_CONTENT" \
          '{msgtype: "markdown", markdown: {content: $content}}')

        curl -s -f -X POST "$WEBHOOK_URL" \
          -H "Content-Type: application/json" \
          -d "$MESSAGE_JSON"
